# docker-desktop.values.yaml
replicaCount: 1

service:
  type: NodePort         # exposes the gateway at localhost:<nodePort>
  port: 80
  nodePort: 32080        # Docker Desktop lets you hit this on localhost

ingress:
  enabled: false         # no Ingress controller required

storage:
  size: 2Gi              # plenty for demos
  storageClass: ""       # Docker Desktop uses the built-in host-path provisioner

auth:
  enabled: false         # for local hacking; repo is open on localhost

tokenkeeper:
  enabled: true
  image: "python:3.12-alpine"
  port: 8080
  nodePort: 32081
  audience: "git-gateway"
  extraEnv: []
  issuer: "https://cognito-idp.us-east-2.amazonaws.com/us-east-2_AE7uogN5r"
  clientIds: "m95vusubvir6psn1mfac61ond"
  verifyUser: podpilot
  postgres:
    host: tokenkeeper-postgres
    db: tokenkeeper
    user: tokenkeeper
    password: changeme