image:
  nginx: "nginx:1.27-alpine"
  fcgiwrap: "ghcr.io/tianon/fcgiwrap:latest"
  git: "alpine/git:2.44"

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx   # set to your ingress controller class
  host: push.podpilot.dev
  tls:
    enabled: true
    secretName: git-gateway-tls   # create or let cert-manager issue

storage:
  size: 10Gi
  storageClass: ""   # let Kubernetes default; override for EBS/GCE-PD

auth:
  # JWT verification is handled by an internal auth_request
  # Provide your OIDC verifier endpoint + audience
  enabled: true
  verifierUrl: "https://podpilot.dev/verify"
  audience: "git-gateway"

tokenkeeper:
  enabled: true
  image: "python:3.12-alpine"
  port: 8080
  nodePort: 32081
  audience: "git-gateway"
  extraEnv: []
  issuer: "https://cognito-idp.us-east-2.amazonaws.com/us-east-2_AE7uogN5r"
  clientIds: "m95vusubvir6psn1mfac61ond"
  verifyUser: podpilot
  postgres:
    host: tokenkeeper-postgres
    db: tokenkeeper
    user: tokenkeeper
    password: changeme # override via secret in production

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
