apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-data-pvc
  labels:
    app: git-gateway
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
