{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.cert .Values.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.cert }}
  tls.key: {{ .Values.ingress.tls.key }}
{{- end }}
