apiVersion: v1
kind: Secret
metadata:
  name: tokenkeeper-postgres-secret
  labels:
    app: tokenkeeper-postgres
type: Opaque
data:
  password: {{ .Values.tokenkeeper.postgres.password | b64enc | quote }}
