apiVersion: v1
kind: Service
metadata:
  name: tokenkeeper
  labels:
    app: tokenkeeper
spec:
  type: NodePort
  ports:
    - port: {{ .Values.tokenkeeper.port }}
      targetPort: {{ .Values.tokenkeeper.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.tokenkeeper.nodePort }}
  selector:
    app: tokenkeeper
